# Indexing and Slicing

In [13]:
# importing numpy
import numpy as np


In [14]:
np.random.seed(0)

In [17]:
a = np.array(np.random.randint(low=10, high=20, size=10))
b = np.array(np.random.randint(low=30, high=50, size=10))
print(a)

[17 16 18 18 11 16 17 17 18 11]


In [16]:
for i in range(len(a)-1):
  print(f'{i+1}item : {a[i]}')

1item : 15
2item : 10
3item : 13
4item : 13
5item : 17
6item : 19
7item : 13
8item : 15
9item : 12


# 2D Array

In [21]:
arr_2d = np.array([a,b])
arr_2d

array([[17, 16, 18, 18, 11, 16, 17, 17, 18, 11],
       [35, 43, 38, 39, 49, 46, 49, 35, 45, 45]])

In [46]:
row, col = arr_2d.shape
for i in range(row):
  for j in range(col):
    print(arr_2d[i,j])

17
16
18
18
11
16
17
17
18
11
35
43
38
39
49
46
49
35
45
45


In [35]:
arr_2d[0 : 2, :5:2]

array([[17, 18, 11],
       [35, 38, 49]])

# Slicing 1D array

In [31]:
a = np.array(np.random.randint(low=10, high=20, size=10))
a

array([10, 12, 13, 18, 11, 13, 13, 13, 17, 10])

In [33]:
a[1:5]

array([12, 18])

In [36]:
a[-3:-1] # left to right

array([13, 17])

In [37]:
a[-3:] # left to right

array([13, 17, 10])

In [38]:
a[:-3] # left to right

array([10, 12, 13, 18, 11, 13, 13])

# Reverse

In [39]:
a[::-1] # right to left

array([10, 17, 13, 13, 13, 11, 18, 13, 12, 10])

# 2D slicing

In [56]:
arr_2d

array([[17, 16, 18, 18, 11, 16, 17, 17, 18, 11],
       [35, 43, 38, 39, 49, 46, 49, 35, 45, 45]])

In [59]:
arr_2d[::,3:6]

array([[18, 11, 16],
       [39, 49, 46]])

# Copy and View

# .copy()

In [51]:
# .copy() method to copy the value of base array
copy_arr = arr_2d.copy()
# hint: np.shares.memory(arr1, arr2)

In [53]:
print(f"""Do original array and copy array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and copy array shares an memory?
Ans: False


In [60]:
# here just assigning the base array to new variable
copy_arr = arr_2d
print(f"""Do original array and copy array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and copy array shares an memory?
Ans: True


# .view()

In [63]:
# .view() method to view the value of base array
view_arr = arr_2d.view()

In [62]:
print(f"""Do original array and view array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and view array shares an memory?
Ans: True
