Load dataset.csv file into list of list using csv reader<br>
Then create a 2d numpy arrray from the list of list.<br>
Extract the first five rows of the numpy array using slicing.<br>
Extract the last five rows of the numpy array using slicing.<br>
Check the shape and dimension of the dataset.<br>
Find some compatible shapes in which we can reshape it.<br>
If we have another numpy array of shape (8, 4341). Can we perform any operations on them? Is it broadcastable?<br>
Find the selling_prices of all cars.<br>
Find the km_driven for all cars.<br>
How can we perform boolean indexing in the given data.<br>

In [1]:
import numpy as np
import csv

In [2]:
with open("car_details.csv","r") as file:
    csv_reader = csv.reader(file)
    dataset = list(csv_reader)
print(dataset)

[['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner'], ['Maruti 800 AC', '2007', '60000', '70000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Maruti Wagon R LXI Minor', '2007', '135000', '50000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Hyundai Verna 1.6 SX', '2012', '600000', '100000', 'Diesel', 'Individual', 'Manual', 'First Owner'], ['Datsun RediGO T Option', '2017', '250000', '46000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Honda Amaze VX i-DTEC', '2014', '450000', '141000', 'Diesel', 'Individual', 'Manual', 'Second Owner'], ['Maruti Alto LX BSIII', '2007', '140000', '125000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Hyundai Xcent 1.2 Kappa S', '2016', '550000', '25000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Tata Indigo Grand Petrol', '2014', '240000', '60000', 'Petrol', 'Individual', 'Manual', 'Second Owner'], ['Hyundai Creta 1.6 VTVT S', '2015', '850000', '25000', 'Petrol', 'Individ

In [3]:
# creating array
array_dataset = np.array(dataset)

In [4]:
# extractinig first five rows
array_dataset[0:5]

array([['name', 'year', 'selling_price', 'km_driven', 'fuel',
        'seller_type', 'transmission', 'owner'],
       ['Maruti 800 AC', '2007', '60000', '70000', 'Petrol',
        'Individual', 'Manual', 'First Owner'],
       ['Maruti Wagon R LXI Minor', '2007', '135000', '50000', 'Petrol',
        'Individual', 'Manual', 'First Owner'],
       ['Hyundai Verna 1.6 SX', '2012', '600000', '100000', 'Diesel',
        'Individual', 'Manual', 'First Owner'],
       ['Datsun RediGO T Option', '2017', '250000', '46000', 'Petrol',
        'Individual', 'Manual', 'First Owner']], dtype='<U58')

In [5]:
# extracting last five rows
rows, columns = array_dataset.shape
array_dataset[rows-5:]

array([['Hyundai i20 Magna 1.4 CRDi (Diesel)', '2014', '409999', '80000',
        'Diesel', 'Individual', 'Manual', 'Second Owner'],
       ['Hyundai i20 Magna 1.4 CRDi', '2014', '409999', '80000',
        'Diesel', 'Individual', 'Manual', 'Second Owner'],
       ['Maruti 800 AC BSIII', '2009', '110000', '83000', 'Petrol',
        'Individual', 'Manual', 'Second Owner'],
       ['Hyundai Creta 1.6 CRDi SX Option', '2016', '865000', '90000',
        'Diesel', 'Individual', 'Manual', 'First Owner'],
       ['Renault KWID RXT', '2016', '225000', '40000', 'Petrol',
        'Individual', 'Manual', 'First Owner']], dtype='<U58')

In [6]:
# shape
array_dataset.shape

(4341, 8)

In [7]:
# dimension
array_dataset.ndim

2

In [8]:
# Find some compatible shapes in which we can reshape it.
array_dataset.reshape(1447, 24)

array([['name', 'year', 'selling_price', ..., 'Individual', 'Manual',
        'First Owner'],
       ['Hyundai Verna 1.6 SX', '2012', '600000', ..., 'Individual',
        'Manual', 'Second Owner'],
       ['Maruti Alto LX BSIII', '2007', '140000', ..., 'Individual',
        'Manual', 'Second Owner'],
       ...,
       ['Ford EcoSport 1.5 TDCi Titanium BSIV', '2015', '530000', ...,
        'Individual', 'Manual', 'Second Owner'],
       ['Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV', '2012', '600000',
        ..., 'Individual', 'Manual', 'Second Owner'],
       ['Maruti 800 AC BSIII', '2009', '110000', ..., 'Individual',
        'Manual', 'First Owner']], dtype='<U58')

# here array of shape (4341, 8) is reshape to (1447, 24) in 2D array

In [9]:
array_dataset.reshape(1447, 8, 3)

array([[['name', 'year', 'selling_price'],
        ['km_driven', 'fuel', 'seller_type'],
        ['transmission', 'owner', 'Maruti 800 AC'],
        ...,
        ['First Owner', 'Maruti Wagon R LXI Minor', '2007'],
        ['135000', '50000', 'Petrol'],
        ['Individual', 'Manual', 'First Owner']],

       [['Hyundai Verna 1.6 SX', '2012', '600000'],
        ['100000', 'Diesel', 'Individual'],
        ['Manual', 'First Owner', 'Datsun RediGO T Option'],
        ...,
        ['First Owner', 'Honda Amaze VX i-DTEC', '2014'],
        ['450000', '141000', 'Diesel'],
        ['Individual', 'Manual', 'Second Owner']],

       [['Maruti Alto LX BSIII', '2007', '140000'],
        ['125000', 'Petrol', 'Individual'],
        ['Manual', 'First Owner', 'Hyundai Xcent 1.2 Kappa S'],
        ...,
        ['First Owner', 'Tata Indigo Grand Petrol', '2014'],
        ['240000', '60000', 'Petrol'],
        ['Individual', 'Manual', 'Second Owner']],

       ...,

       [['Ford EcoSport 1.5 TDCi Tita

# here array of reshape (1447, 24) 2D is again reshape to (1447, 8, 3) in 3D array

In [10]:
array_dataset

array([['name', 'year', 'selling_price', ..., 'seller_type',
        'transmission', 'owner'],
       ['Maruti 800 AC', '2007', '60000', ..., 'Individual', 'Manual',
        'First Owner'],
       ['Maruti Wagon R LXI Minor', '2007', '135000', ..., 'Individual',
        'Manual', 'First Owner'],
       ...,
       ['Maruti 800 AC BSIII', '2009', '110000', ..., 'Individual',
        'Manual', 'Second Owner'],
       ['Hyundai Creta 1.6 CRDi SX Option', '2016', '865000', ...,
        'Individual', 'Manual', 'First Owner'],
       ['Renault KWID RXT', '2016', '225000', ..., 'Individual',
        'Manual', 'First Owner']], dtype='<U58')

In [11]:
array_dataset.shape

(4341, 8)

# If we have another numpy array of shape (8, 4341). Can we perform any operations on them? Is it broadcastable?

-> yes we can perform operation  of another array with shape(8, 4341) and it is broadcastable because to perform matrix multiplication, the first matrix must have the same number of columns as the second matrix has rows.

In [12]:
# for example
a = np.array([[12,12,12],[12,34,4343]])
b = np.array([[12,34,12,],[12,321,14],[3,1,4]])

In [13]:
a.shape

(2, 3)

In [14]:
b.shape

(3, 3)

# here, array a has same number of columns as number of rows of b so, a and b can perform an operation and broadcastable

In [15]:
c = np.dot(a,b)
print(c)

[[  324  4272   360]
 [13581 15665 17992]]


# Find the selling_prices of all cars.

In [16]:
array_dataset[:1]

array([['name', 'year', 'selling_price', 'km_driven', 'fuel',
        'seller_type', 'transmission', 'owner']], dtype='<U58')

In [17]:
# Find the selling_prices of all cars.
array_dataset[::,:3:2]

array([['name', 'selling_price'],
       ['Maruti 800 AC', '60000'],
       ['Maruti Wagon R LXI Minor', '135000'],
       ...,
       ['Maruti 800 AC BSIII', '110000'],
       ['Hyundai Creta 1.6 CRDi SX Option', '865000'],
       ['Renault KWID RXT', '225000']], dtype='<U58')

In [18]:
selling_price = array_dataset[::, :3:2].tolist()
selling_price

[['name', 'selling_price'],
 ['Maruti 800 AC', '60000'],
 ['Maruti Wagon R LXI Minor', '135000'],
 ['Hyundai Verna 1.6 SX', '600000'],
 ['Datsun RediGO T Option', '250000'],
 ['Honda Amaze VX i-DTEC', '450000'],
 ['Maruti Alto LX BSIII', '140000'],
 ['Hyundai Xcent 1.2 Kappa S', '550000'],
 ['Tata Indigo Grand Petrol', '240000'],
 ['Hyundai Creta 1.6 VTVT S', '850000'],
 ['Maruti Celerio Green VXI', '365000'],
 ['Chevrolet Sail 1.2 Base', '260000'],
 ['Tata Indigo Grand Petrol', '250000'],
 ['Toyota Corolla Altis 1.8 VL CVT', '1650000'],
 ['Maruti 800 AC', '60000'],
 ['Maruti Wagon R LXI Minor', '135000'],
 ['Hyundai Verna 1.6 SX', '600000'],
 ['Datsun RediGO T Option', '250000'],
 ['Honda Amaze VX i-DTEC', '450000'],
 ['Maruti Alto LX BSIII', '140000'],
 ['Hyundai Xcent 1.2 Kappa S', '550000'],
 ['Tata Indigo Grand Petrol', '240000'],
 ['Hyundai Creta 1.6 VTVT S', '850000'],
 ['Maruti Celerio Green VXI', '365000'],
 ['Chevrolet Sail 1.2 Base', '260000'],
 ['Tata Indigo Grand Petrol', 

In [19]:
for i in array_dataset:
    print(f"{i[0]}  {i[2]}")

name  selling_price
Maruti 800 AC  60000
Maruti Wagon R LXI Minor  135000
Hyundai Verna 1.6 SX  600000
Datsun RediGO T Option  250000
Honda Amaze VX i-DTEC  450000
Maruti Alto LX BSIII  140000
Hyundai Xcent 1.2 Kappa S  550000
Tata Indigo Grand Petrol  240000
Hyundai Creta 1.6 VTVT S  850000
Maruti Celerio Green VXI  365000
Chevrolet Sail 1.2 Base  260000
Tata Indigo Grand Petrol  250000
Toyota Corolla Altis 1.8 VL CVT  1650000
Maruti 800 AC  60000
Maruti Wagon R LXI Minor  135000
Hyundai Verna 1.6 SX  600000
Datsun RediGO T Option  250000
Honda Amaze VX i-DTEC  450000
Maruti Alto LX BSIII  140000
Hyundai Xcent 1.2 Kappa S  550000
Tata Indigo Grand Petrol  240000
Hyundai Creta 1.6 VTVT S  850000
Maruti Celerio Green VXI  365000
Chevrolet Sail 1.2 Base  260000
Tata Indigo Grand Petrol  250000
Toyota Corolla Altis 1.8 VL CVT  1650000
Maruti Ciaz VXi Plus  585000
Hyundai Venue SX Opt Diesel  1195000
Chevrolet Enjoy TCDi LTZ 7 Seater  390000
Jaguar XF 2.2 Litre Luxury  1964999
Mercedes-Ben

# Find the km_driven for all cars.

In [20]:
# Find the km_driven for all cars.
array_dataset[::, :5:3]

array([['name', 'km_driven'],
       ['Maruti 800 AC', '70000'],
       ['Maruti Wagon R LXI Minor', '50000'],
       ...,
       ['Maruti 800 AC BSIII', '83000'],
       ['Hyundai Creta 1.6 CRDi SX Option', '90000'],
       ['Renault KWID RXT', '40000']], dtype='<U58')

In [21]:
km_driven = array_dataset[::, :3:2].tolist()
km_driven

[['name', 'selling_price'],
 ['Maruti 800 AC', '60000'],
 ['Maruti Wagon R LXI Minor', '135000'],
 ['Hyundai Verna 1.6 SX', '600000'],
 ['Datsun RediGO T Option', '250000'],
 ['Honda Amaze VX i-DTEC', '450000'],
 ['Maruti Alto LX BSIII', '140000'],
 ['Hyundai Xcent 1.2 Kappa S', '550000'],
 ['Tata Indigo Grand Petrol', '240000'],
 ['Hyundai Creta 1.6 VTVT S', '850000'],
 ['Maruti Celerio Green VXI', '365000'],
 ['Chevrolet Sail 1.2 Base', '260000'],
 ['Tata Indigo Grand Petrol', '250000'],
 ['Toyota Corolla Altis 1.8 VL CVT', '1650000'],
 ['Maruti 800 AC', '60000'],
 ['Maruti Wagon R LXI Minor', '135000'],
 ['Hyundai Verna 1.6 SX', '600000'],
 ['Datsun RediGO T Option', '250000'],
 ['Honda Amaze VX i-DTEC', '450000'],
 ['Maruti Alto LX BSIII', '140000'],
 ['Hyundai Xcent 1.2 Kappa S', '550000'],
 ['Tata Indigo Grand Petrol', '240000'],
 ['Hyundai Creta 1.6 VTVT S', '850000'],
 ['Maruti Celerio Green VXI', '365000'],
 ['Chevrolet Sail 1.2 Base', '260000'],
 ['Tata Indigo Grand Petrol', 

In [22]:
for i in array_dataset:
    print(f"{i[0]}  {i[3]}")

name  km_driven
Maruti 800 AC  70000
Maruti Wagon R LXI Minor  50000
Hyundai Verna 1.6 SX  100000
Datsun RediGO T Option  46000
Honda Amaze VX i-DTEC  141000
Maruti Alto LX BSIII  125000
Hyundai Xcent 1.2 Kappa S  25000
Tata Indigo Grand Petrol  60000
Hyundai Creta 1.6 VTVT S  25000
Maruti Celerio Green VXI  78000
Chevrolet Sail 1.2 Base  35000
Tata Indigo Grand Petrol  100000
Toyota Corolla Altis 1.8 VL CVT  25000
Maruti 800 AC  70000
Maruti Wagon R LXI Minor  50000
Hyundai Verna 1.6 SX  100000
Datsun RediGO T Option  46000
Honda Amaze VX i-DTEC  141000
Maruti Alto LX BSIII  125000
Hyundai Xcent 1.2 Kappa S  25000
Tata Indigo Grand Petrol  60000
Hyundai Creta 1.6 VTVT S  25000
Maruti Celerio Green VXI  78000
Chevrolet Sail 1.2 Base  35000
Tata Indigo Grand Petrol  100000
Toyota Corolla Altis 1.8 VL CVT  25000
Maruti Ciaz VXi Plus  24000
Hyundai Venue SX Opt Diesel  5000
Chevrolet Enjoy TCDi LTZ 7 Seater  33000
Jaguar XF 2.2 Litre Luxury  28000
Mercedes-Benz New C-Class 220 CDI AT  590

# How can we perform boolean indexing in the given data.

# Applying Universal Functions and Aggregations

In [33]:
#removing zero indes data
data_set = [dataset[index] for index in range(1,len(dataset))]
selling_price =[item[2] for item in data_set]
selling_price_array = np.array(selling_price, dtype =float)
print(type(selling_price))
print(selling_price_array)

<class 'list'>
[ 60000. 135000. 600000. ... 110000. 865000. 225000.]


# applying universal function
<b>.sin(), .cos(), .tan()

In [37]:

# Sine
sin_value = np.sin(selling_price_array)
print(f"Sine : {sin_value}")

# Cosine
cosin_value = np.cos(selling_price_array)
print(f"Cosine : {cosin_value}")

# tangent
tan_value = np.tan(selling_price_array)
print(f"Tangent : {tan_value}")

Sine : [ 0.95746675 -0.4964549  -0.21289653 ...  0.27138063  0.16123894
 -0.7616464 ]
Cosine : [-0.28854362  0.86806252  0.97707475 ...  0.9624721   0.9869154
  0.64799287]
Tangent : [-3.31827382 -0.57191146 -0.21789175 ...  0.28196208  0.16337666
 -1.17539317]


In [36]:
# Square root
sqrt_ans = np.sqrt(selling_price_array)
print('Square Root:', sqrt_ans)

Square Root: [244.94897428 367.42346142 774.59666924 ... 331.66247904 930.05376189
 474.34164903]


# Aggregation

In [38]:
# mean()
np.mean(selling_price_array)

504127.3117511521

In [39]:
# median()
np.median(selling_price_array)

350000.0

In [44]:
# min()
np.min(selling_price_array)

20000.0

In [45]:
# argmin()
np.argmin(selling_price_array)

2662

In [46]:
# max()
np.max(selling_price_array)

8900000.0

In [48]:
# argmax()
np.argmax(selling_price_array)

3872