# Numpy
* stands for numerical python
* numpy is a python library used for working with arrays
* has function for working in domain of linear algebra, fourier tansfrom and matrices
* numpy array is a collection of homogeneous data types stored in contiguous memory location
* written parially in python, but parts that require fast computation are written in C or C++

# Why is Numpy is fast?
* An array is a collection of homogeneous data types that are stored in contiguous memory location
* Vectorized operations are possible in NumPy
* NUmpy package integrates C,C++ and Fortran codes in python

In [36]:
import numpy as np

# create numpy array vai 1D list

In [37]:

np.random.seed(0)
list1 = np.random.randint(low=1 , high=20, size= 10)
arr = np.array(list1)
print(arr)

[13 16  1  4  4  8 10 19  5  7]


# checking the type af arr

In [38]:

type(arr)

numpy.ndarray

# create numpy array vai 1D list

In [39]:

list2 = np.random.randint(low=10, high=30,size=10)
arr2 = np.array([list1,list2], dtype='float32')
arr2

array([[13., 16.,  1.,  4.,  4.,  8., 10., 19.,  5.,  7.],
       [22., 11., 16., 17., 24., 27., 15., 23., 18., 19.]], dtype=float32)

# .shape

In [40]:
# shape
arr2.shape

(2, 10)

# .ndim

In [41]:
# dimension
arr2.ndim

2

# .zeros()

In [42]:
# zeros()
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
# zeros()
np.zeros((3,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# .ones()

In [44]:
# ones()
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
# ones()
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# .full()

In [32]:
# full()
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [33]:
# full()
np.full((2,2), ['read','write'])

array([['read', 'write'],
       ['read', 'write']], dtype='<U5')

In [34]:
# full()
np.full((2,10), [list1,list2])

array([[13, 16,  1,  4,  4,  8, 10, 19,  5,  7],
       [22, 11, 16, 17, 24, 27, 15, 23, 18, 19]])

# .arrange()

In [35]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# .random()

In [79]:
np.random.random((3,5))

array([[0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491]])

# .normal()

In [55]:
np.random.normal(loc=0, scale=1,size=(3,3))

array([[ 1.46274045,  1.53502913,  0.56644004],
       [ 0.14926509, -1.078278  ,  1.39547227],
       [ 1.78748405, -0.56951726,  0.17538653]])

# .randint()

In [51]:
np.random.randint(low=0, high=10, size=(3,3))

array([[4, 7, 3],
       [2, 7, 2],
       [0, 0, 4]])

# Creating sample_array

In [56]:
sample_array= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [57]:
# Printing the dimension of numpy
print(f"The dimension of {sample_array} is {sample_array.ndim}")

The dimension of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 2


In [69]:
sample_array.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [66]:
sample_array= np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
])

In [67]:
print(f"The dimension of {sample_array} is {sample_array.ndim}")

The dimension of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 3


In [68]:
sample_array.shape

(1, 3, 3)

In [70]:
print(f"The size of {sample_array} is {sample_array.size}")

The size of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 9


In [71]:
print(f"The data type of {sample_array} is {sample_array.dtype}")

The data type of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is int32


In [72]:
print(f"The item size of {sample_array} is {sample_array.itemsize}")

The item size of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 4


In [80]:
name = ["nares",1,2]
arr = np.array(name)

In [81]:
arr

array(['nares', '1', '2'], dtype='<U11')