# Indexing and Slicing

In [1]:
# importing numpy
import numpy as np


In [2]:
np.random.seed(0)

In [3]:
a = np.array(np.random.randint(low=10, high=20, size=10))
b = np.array(np.random.randint(low=30, high=50, size=10))
print(a)

[15 10 13 13 17 19 13 15 12 14]


In [4]:
for i in range(len(a)-1):
  print(f'{i+1}item : {a[i]}')

1item : 15
2item : 10
3item : 13
4item : 13
5item : 17
6item : 19
7item : 13
8item : 15
9item : 12


# 2D Array

In [5]:
arr_2d = np.array([a,b])
arr_2d

array([[15, 10, 13, 13, 17, 19, 13, 15, 12, 14],
       [36, 42, 31, 36, 37, 44, 47, 35, 43, 38]])

In [6]:
row, col = arr_2d.shape
for i in range(row):
  for j in range(col):
    print(arr_2d[i,j])

15
10
13
13
17
19
13
15
12
14
36
42
31
36
37
44
47
35
43
38


In [7]:
arr_2d[0 : 2, :5:2]

array([[15, 13, 17],
       [36, 31, 37]])

# Slicing 1D array

In [8]:
a = np.array(np.random.randint(low=10, high=20, size=10))
a

array([19, 14, 13, 10, 13, 15, 10, 12, 13, 18])

In [9]:
a[1:5]

array([14, 13, 10, 13])

In [10]:
a[-3:-1] # left to right

array([12, 13])

In [11]:
a[-3:] # left to right

array([12, 13, 18])

In [12]:
a[:-3] # left to right

array([19, 14, 13, 10, 13, 15, 10])

# Reverse

In [13]:
a[::-1] # right to left

array([18, 13, 12, 10, 15, 13, 10, 13, 14, 19])

# 2D slicing

In [14]:
arr_2d

array([[15, 10, 13, 13, 17, 19, 13, 15, 12, 14],
       [36, 42, 31, 36, 37, 44, 47, 35, 43, 38]])

In [15]:
arr_2d[::,3:6]

array([[13, 17, 19],
       [36, 37, 44]])

# Copy and View

# .copy()

In [16]:
# .copy() method to copy the value of base array
copy_arr = arr_2d.copy()
# hint: np.shares.memory(arr1, arr2)

In [17]:
print(f"""Do original array and copy array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and copy array shares an memory?
Ans: False


In [18]:
# here just assigning the base array to new variable
copy_arr = arr_2d
print(f"""Do original array and copy array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and copy array shares an memory?
Ans: True


# .view()

In [19]:
# .view() method to view the value of base array
view_arr = arr_2d.view()

In [20]:
print(f"""Do original array and view array shares an memory?
Ans: {np.shares_memory(arr_2d, copy_arr)}""")

Do original array and view array shares an memory?
Ans: True
