# Numpy
* stands for numerical python
* numpy is a python library used for working with arrays
* has function for working in domain of linear algebra, fourier tansfrom and matrices
* numpy array is a collection of homogeneous data types stored in contiguous memory location
* written parially in python, but parts that require fast computation are written in C or C++

# Why is Numpy is fast?
* An array is a collection of homogeneous data types that are stored in contiguous memory location
* Vectorized operations are possible in NumPy
* NUmpy package integrates C,C++ and Fortran codes in python

In [1]:
import numpy as np

# create numpy array vai 1D list

In [2]:

np.random.seed(0)
list1 = np.random.randint(low=1 , high=20, size= 10)
arr = np.array(list1)
print(arr)

[13 16  1  4  4  8 10 19  5  7]


# checking the type af arr

In [3]:

type(arr)

numpy.ndarray

# create numpy array vai 1D list

In [4]:

list2 = np.random.randint(low=10, high=30,size=10)
arr2 = np.array([list1,list2], dtype='float32')
arr2

array([[13., 16.,  1.,  4.,  4.,  8., 10., 19.,  5.,  7.],
       [22., 11., 16., 17., 24., 27., 15., 23., 18., 19.]], dtype=float32)

# .shape
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.arr.<br>
Syntax:
```python
array.shape
```

In [5]:
# shape
arr2.shape

(2, 10)

# .ndim
Attribute that return Number of array dimensions.<br>
Syntax:
```python
array.ndim
```

In [6]:
# dimension
arr2.ndim

2

# .zeros()
Python numpy.zeros() function returns a new array of given shape and type, where the element's value as 0.<br>
Syntax:
```python
numpy.zeros(shape, dtype=float, order='C', *, like=None)
```


In [7]:
# zeros()
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# zeros()
np.zeros((3,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# .ones()
Returns Array of ones with the given shape, dtype, and order.<br>
Syntax:
```python
numpy.ones(shape, dtype=None, order='C', *, like=None)
```

In [9]:
# ones()
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
# ones()
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# .full()
Array of fill_value with the given shape, dtype, and order.<br>
Syntax:
```python
    numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
```

In [11]:
# full()
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# full()
np.full((2,2), ['read','write'])

array([['read', 'write'],
       ['read', 'write']], dtype='<U5')

In [13]:
# full()
np.full((2,10), [list1,list2])

array([[13, 16,  1,  4,  4,  8, 10, 19,  5,  7],
       [22, 11, 16, 17, 24, 27, 15, 23, 18, 19]])

# .arrange()
Return evenly spaced values within a given interval.<br>
Syntax:
```python
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
```

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# .random()
Return random value of given shape.<br>
Syntax:
```python
numpy.random.random(shape, dtype=None)
```

In [15]:
np.random.random((3,5))

array([[0.64817187, 0.36824154, 0.95715516, 0.14035078, 0.87008726],
       [0.47360805, 0.80091075, 0.52047748, 0.67887953, 0.72063265],
       [0.58201979, 0.53737323, 0.75861562, 0.10590761, 0.47360042]])

# .normal()
Draw random samples from a normal (Gaussian) distribution.<br>
Syntax:
```python
random.normal(loc=0.0, scale=1.0, size=None)
```

In [16]:
np.random.normal(loc=0, scale=1,size=(3,3))

array([[ 0.59124281, -0.7827755 , -0.44423283],
       [-0.34518616, -0.88180055, -0.44265324],
       [-0.5409163 , -1.32322737, -0.11279892]])

# .randint()
Return random integers from low (inclusive) to high (exclusive).<br>
Syntax:
```python
random.randint(low, high=None, size=None, dtype=int)
```

In [17]:
np.random.randint(low=0, high=10, size=(3,3))

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]])

# Creating sample_array

In [18]:
sample_array= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
# Printing the dimension of numpy
print(f"The dimension of {sample_array} is {sample_array.ndim}")

The dimension of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 2


In [20]:
sample_array.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
sample_array= np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
])

In [22]:
print(f"The dimension of {sample_array} is {sample_array.ndim}")

The dimension of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 3


In [23]:
sample_array.shape

(1, 3, 3)

In [24]:
print(f"The size of {sample_array} is {sample_array.size}")

The size of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 9


In [25]:
print(f"The data type of {sample_array} is {sample_array.dtype}")

The data type of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is int32


In [26]:
print(f"The item size of {sample_array} is {sample_array.itemsize}")

The item size of [[[1 2 3]
  [4 5 6]
  [7 8 9]]] is 4


In [27]:
name = ["nares",1,2]
arr = np.array(name)

In [28]:
arr

array(['nares', '1', '2'], dtype='<U11')

# Why arr is printed all string?
NumPy array arr are printed as strings is because NumPy arrays require all elements to be of the same data type. When you create an array from a list that contains elements of different types (like strings and integers in your case), NumPy will automatically convert all elements to a common data type that can accommodate all the elements.<br>
since one of the elements in the name list is a string ("nares"), NumPy converts all elements to strings to maintain a uniform data type within the array. As a result, both the integer 1 and 2 are converted to strings as well.
# To maintain their original data types:
By specifying dtype=object, you're telling NumPy to treat each element of the array as a generic Python object.  However, note that operating on arrays with dtype=object can sometimes be less efficient compared to arrays with homogeneous data types.

In [29]:
name = ["nares",1,2]
arr = np.array(name, dtype='object')
print(arr)

['nares' 1 2]


In [30]:
type(arr)

numpy.ndarray

In [31]:
for item in arr:
    print(type(item))

<class 'str'>
<class 'int'>
<class 'int'>


# making list as array homogeneous data type properties

In [32]:
class Array:
    def array_list(self, data_list):
      d_type = []
      array_list = []
      for item in data_list:
        d_type.append(type(item))
      if str in d_type:
        for item in data_list:
          array_list.append(str(item))
      elif float in d_type:
        for item in data_list:
          array_list.append(float(item))
      elif bool in d_type:
        for item in data_list:
          array_list.append(int(item))
      else:
        for item in data_list:
          array_list.append(int(item))
        
      return array_list


if __name__ == "__main__":
    l = [True , False, 1,3.4,"ram"]
    arr= Array()
    print(arr.array_list(data_list=l))
    print(type(arr))

['True', 'False', '1', '3.4', 'ram']
<class '__main__.Array'>


In [33]:
import numpy as np
arra_01 = np.array([], dtype='int32')

In [34]:
type(arra_01)

numpy.ndarray

In [35]:
arr= np.array([1,2,3,4, "ste"], dtype=int)

ValueError: invalid literal for int() with base 10: 'ste'