# .reshape()

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
np.reshape(arr,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr.reshape(1, -1) # row matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [5]:
arr.reshape(-1,1) # column matrix

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# .reshape() 1D to 2D


In [6]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Can we reshape to any shape?
* yes, as long as element required for reshaping are equal in both shapes.


In [9]:
a = np.array([1,2,3,4,5,6,7,8,])
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
a.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
a.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Joining Arrays
* Array joining means putting content of two or more array in a single array.
* In SQL we join tables based on keys, whereas in NumPy we join arrays by axes.
* Array joining can be done in two ways:<br>
      * Concatenation: using concatenate() function <br>
      * Stacking: using stack() function

# Concatenation
* We pass sequence of arrays that we want to the concatenate() function.
* After concatenating dimensions of resulting array eill be same as that of individual array.
syntax:
```python
np.concatenate((a1,a2,....), axis=0, out=None)
```
where, a1,a2,...: Sequence of array_like.<br>
axis: row wise or column wise


In [40]:
arr1 = np.array([1,1,1,1])
aar2 = np.array([2,2,2,2])

aar2.shape

(4,)

In [41]:
concat =  np.column_stack([arr1, aar2])

In [42]:
concat

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [36]:
arr1 = np.array([[1,1,1,1]])
arrr2 = np.array([[2,2,2,2]])
# row wise(axis = 0)
concat = np.concatenate((arr1,arrr2), axis=0)
concat

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [37]:
# column wise (axis = 1)
concat_c = np.concatenate((arr1,arrr2), axis = 1 )
concat_c

array([[1, 1, 1, 1, 2, 2, 2, 2]])

# Splitting Array
* Splitting is reverse operation of joining
* Joining merges multiple arrays into one.
* Splitting breaks one array into multiple one.
* Can be implemented using numpy function:
  syntax:<br>
```python
numpy.split()
numpy.array_split()
```

In [45]:
ar1 = np.array([1,2,3,4,5,6])
np.split(ar1, 4)

ValueError: array split does not result in an equal division

In [46]:
np.array_split(ar1,5)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

# Splitting 2D array(axis = 0)

In [47]:
ary1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

In [49]:
ary1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [50]:
np.array_split(ary1, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [51]:
np.array_split(ary1,4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [52]:
np.split(ary1, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [53]:
np.split(ary1, 4)


ValueError: array split does not result in an equal division

In [56]:
np.array_split(ary1, 3, axis =1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [57]:
np.array_split(ary1, 4, axis =1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int32)]

In [58]:
np.split(ary1, 3, axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [59]:
np.split(ary1, 4, axis = 1)


ValueError: array split does not result in an equal division

# Numpy Universal Functiton(Ufuncs) 
* looping over the array to perfor repeated task like addition, substraction, etc
* Computatiokn time to perform such repeated task increases with relatively larger data.
* NumPy makes this faster by using vectorized operations, implemented through ufuncs.
* Types:<br>
      * Unary Ufuncs<br>
      * Binary Ufuncs<br>


In [66]:
import time
x1 = np.arange(1, 1000000)
x2 = np.arange(1, 1000000)

In [67]:
mul = np.zeros(x1.shape)
start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]

end_time = time.process_time()

print(end_time - start_time)

C:\Users\Thinkpad\AppData\Local\Temp\ipykernel_9400\657081681.py:5: RuntimeWarning: overflow encountered in scalar multiply
  mul[i] = x1[i] * x2[i]


4.53125


In [68]:
# Broadcasting with Scalars
a = np.array([1,3,4])
b = 2
print(a + b)


[3 5 6]


In [70]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])

print(f"the shape of a : {a.shape}")
print(f"the shape of b : {b.shape}")

c = a+ b
print(c)

the shape of a : (3,)
the shape of b : (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [71]:
a= np.array([1,3])
b= np.array([1,2,3])
a+ b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

# .eye()

In [80]:
a = np.array(3)
np.eye(a, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])